# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50b4127e8100cc6864a231acfa92bf7bb3c2d940cbc0ddf7b8595bd24ad15a986725ae9f8cbdc877875120f6cea75df4569429b9a956c7b8f004c4fa34c17bf9

test:
  secret_key_base: 4c3215e3a53015fd9e71dce358d86cc046fc04c90d0a0d32718d580541035866c8d7acf06096a9075f43ff802c1939d22f663a0b0ca67832e2623cbe16f0a6a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
